name: great_circle_distance
description: Calculate the great-circle distance on the Earth having a pair of Latitude,Longitude points using the Spherical law of cosines, Haversine formula or Vincenty`s formula
version: 1.0.0
homepage: https://techbuzs.ml
author: Oreofe Solarin <oreofesolarin@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: '^1.11.1'